default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>

development:
  <<: *default
  database: dev
  host: db
  username: postgres
  password:

test:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3

production:
  <<: *default
  database: legit_news_prod
  username: legit_news_prod
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
